import "vuetify/styles"
import "@mdi/font/css/materialdesignicons.css"
import { createVuetify } from "vuetify"
import {
  VAlert,
  VApp,
  VAppBar,
  VAppBarTitle,
  VBtn,
  VCard,
  VCardActions,
  VCardSubtitle,
  VCardText,
  VCardTitle,
  VCheckbox,
  VCol,
  VCombobox,
  VContainer,
  VDialog,
  VDivider,
  VExpandTransition,
  VExpansionPanel,
  VExpansionPanels,
  VForm,
  VIcon,
  VLabel,
  VLayout,
  VList,
  VListItem,
  VListSubheader,
  VMain,
  VMenu,
  VNumberInput,
  VRow,
  VSelect,
  VSlider,
  VSlideYTransition,
  VSpacer,
  VTab,
  VTabs,
  VTabsWindow,
  VTabsWindowItem,
  VTextarea,
  VTextField,
  VWindow,
  VWindowItem,
} from "vuetify/components"
import * as directives from "vuetify/directives"

import { createApp } from "vue"
import App from "./App.vue"
import router from "./router"
import { createPinia } from "pinia"

const vuetify = createVuetify({
  components: {
    VSelect,
    VTabs,
    VCombobox,
    VTabsWindow,
    VTab,
    VCardActions,
    VLayout,
    VForm,
    VAppBarTitle,
    VMain,
    VContainer,
    VAlert,
    VSlideYTransition,
    VLabel,
    VRow,
    VTabsWindowItem,
    VCol,
    VAppBar,
    VWindow,
    VTextField,
    VWindowItem,
    VApp,
    VDialog,
    VTextarea,
    VCard,
    VCardText,
    VDivider,
    VBtn,
    VMenu,
    VCardTitle,
    VCardSubtitle,
    VList,
    VIcon,
    VListItem,
    VSpacer,
    VListSubheader,
    VExpandTransition,
    VCheckbox,
    VNumberInput,
    VSlider,
    VExpansionPanel,
    VExpansionPanels,
  },
  icons: {
    defaultSet: "mdi",
  },
  directives,
})

const pinia = createPinia()

const app = createApp(App).use(vuetify).use(router).use(pinia).mount("#app")
